Congyu/restructure
Apollo1840/StudyTimeBoard pull request #4
Opened 2021-03-07 23:02 UTC by Apollo1840

@changdiqing  check this out and merge it to the master pls.

2021-03-08 21:46 UTC, changdiqing commented on backend/studytimeboard/routes.py
> +# depracated
deprecated

2021-03-08 21:47 UTC, changdiqing commented on backend/studytimeboard/routes.py
> +# depracated
deprecated

2021-03-08 21:54 UTC, changdiqing requested changes
- .pyc files are tmp files and should not be commited
 - stb_app_backend.log: if only serves as logger then is not so important for other developers, you can consider to ignore it as well.

2021-03-09 09:28 UTC, Apollo1840 commented on backend/studytimeboard/routes.py
> +# depracated
register 原逻辑暂时保留，以对照其逻辑，对react继续开发。

2021-03-09 09:34 UTC, Apollo1840 commented
> * .pyc files are tmp files and should not be commited
> * stb_app_backend.log: if only serves as logger then is not so important for other developers, you can consider to ignore it as well.

参照你的上一个commit, 应该是ignore掉了的，没见到相关文件。

2021-03-09 09:36 UTC, merged