Sa li/dev/fr bc/add confirm and show password on register page
Apollo1840/StudyTimeBoard pull request #81
Opened 2021-05-15 15:39 UTC by theSaLi

Add confirm and show password on register page.
Had to use <InputGroup> to add the show password button.
Add a logic to validate the username and password.
Please review, thanks.
![image](https://user-images.githubusercontent.com/44193165/118369666-883e9980-b5a4-11eb-870a-e3f3f687a995.png)

2021-05-16 21:27 UTC, changdiqing commented on frontend/src/components/registerview/RegisterView.jsx
> +      password_type: 'password'
- [ ] Comparing password_type as string looks like an antipattern to me. If we have only two statuses, I would suggest using boolean i.e. state.passwordVisible, and check if it is true. If we have more than 2 statuses, I would create an **enum** to store them. One way to use enum in JS is to simply [create a JS object and freeze it](https://stackoverflow.com/questions/287903/what-is-the-preferred-syntax-for-defining-enums-in-javascript)

2021-05-16 21:31 UTC, changdiqing requested changes
Looks pretty good to me, I left one suggestion as comment.

2021-05-17 21:02 UTC, theSaLi commented
Modified as suggested, please review again. Thanks.

2021-05-18 17:27 UTC, Apollo1840 commented
@theSaLi There is no modification that can be observed from my side, maybe push it again?

2021-05-18 17:34 UTC, merged